### ISSUE TITLE
When Submitting a Curl I get `Error performing SELECT` but the post request does work

### ISSUE THREAD

**Issue by Tsangares** [iot2tangle/Keepy#9] opened 2020-11-12 08:09 UTC
I setup the gateway, and the nodejs server.

When posting, 
`curl --location --request POST 'YOUR_KEEPY_HOST:3002/messages' --header 'Content-Type: application/json' --data-raw '{ "iot2tangle": [ { "sensor": "Gyroscope", "data": [ { "x": "4514" }, { "y": "244" }, { "z": "-1830" } ] }, { "sensor": "Acoustic", "data": [ { "mp": "1" } ] } ], "device": "DEVICE_ID_1", "timestamp": 1558511111 }'`

I receive the response , `Error performing SELECT`, but when I check http://localhost:3002/messages, they have successfully posted.

**Comment by demichele** [comment] 2020-11-12 13:37
Hey @Tsangares! Thanks for reporting. Are you using the last version of Keepy. Please pull from the repo, we added some new features. Also, are the datasets you see in http://localhost:3002/messages showing their channel id?

**Comment by eduardopelitti** [comment] 2020-11-12 18:46
Hi @Tsangares, aside from what @demichele mentions, do you have an integer value for `BUFFER_SIZE` in the `.env` file when running Keepy?

With this error, the data will, as you mention, be inserted into the DB, but not sent over to the Gateway because a subsequent query fails (and so you get the `Error performing SELECT` error message). You can check this by querying the data and noticing that there's no `channelId` value associated with the object.

My guess is that environment variable may be missing or set to an invalid value.

If that is the case, then I think we should probably define a fallback value for this environment variable and return a warning that the value is unset or invalid.

**Comment by demichele** [comment] 2020-11-16 17:25
I was able to reproduce the error by following what @eduardopelitti said and I think that was the issue. Therefore, I am closing this issue.

**Closed by demichele** 2020-11-16 17:25 UTC

**Comment by Tsangares** [comment] 2020-11-17 20:13
Yes, I forgot to copy `cp .env.example .env` and change then adust `GATEWAY_URL`.
